apiVersion: v1
kind: ConfigMap
metadata:
  name: __APP_NAME__-config
  namespace: __NAMESPACE__
  labels:
    app: __APP_NAME__
    version: "__VERSION__"
data:
  # Valores por defecto, sobreescribir seg√∫n ambiente
  BONOS_DATASOURCE_URL: ""
  BONOS_DATASOURCE_DRIVER: "com.ibm.as400.access.AS400JDBCDriver"
  BONOS_DATASOURCE_LOGIN_TIMEOUT: ""
  BONOS_AS400_SP: "AUBONB1(?,?)"
  BONOS_CODIGO_APLICACION: "BO"
  BONOS_CODIGO_SWITCH: "0020"
  BONOS_CODIGO_NOVEDAD_CREAR: "01"
  BONOS_CODIGO_NOVEDAD_ACTIVAR: "02"
  BONOS_CODIGO_NOVEDAD_CONSULTAR: "03"
  BONOS_CODIGO_TX_ACTIVACION: "421000"
  BONOS_DISPOSITIVO_ACTIVACION: "02"
  BONOS_TIPO_TX_ACTIVACION: "0200"
  BONOS_NUMERO_BIN_CONSULTAR: "000000"
  BONOS_DOCUMENTO_CC: "01"
  BONOS_DOCUMENTO_NI: "02"
  BONOS_DOCUMENTO_CE: "03"
  BONOS_DOCUMENTO_TI: "04"
  BONOS_DOCUMENTO_PS: "05"
  BONOS_DOCUMENTO_NU: "09"
  BONOS_DOCUMENTO_RC: "19"
  BONOS_CODIGO_E01: "E01"
  BONOS_CODIGO_E03: "E03"
  BONOS_CODIGO_E08: "E08"
  BONOS_CODIGO_E09: "E09"
  BONOS_CODIGO_E10: "E10"
  BONOS_CODIGO_E11: "E11"
  BONOS_CODIGO_E12: "E12"
  BONOS_DESCRIPCION_E01: "Error en estructura de la peticion"
  BONOS_DESCRIPCION_E03: "Error en transformaciones"
  BONOS_DESCRIPCION_E08: "Error de conexion con el proveedor"
  BONOS_DESCRIPCION_E09: "Error interno del servicio"
  BONOS_DESCRIPCION_E10: "Error de Time Out"
  BONOS_DESCRIPCION_E11: "La consulta no arroja resultados"
  BONOS_DESCRIPCION_E12: "Comercio Bloqueado"
  HTTP_OK: "200"
  HTTP_ERROR_GENERAL: "500"
  HTTP_ERROR_ESTRUCTURA: "400"
