apiVersion: v1
kind: Secret
metadata:
  name: __APP_NAME__-secret
  namespace: __NAMESPACE__
  labels:
    app: __APP_NAME__
    version: "__VERSION__"
type: Opaque
data:
  BONOS_DATASOURCE_USER: "UkJNQlVQUlBDSQ==" # RBMBUPRPCI
  BONOS_DATASOURCE_PASSWORD: "dXN1YXJpbzE=" # usuario1
