apiVersion: v1
kind: Service
metadata:
  name: __APP_NAME__
  namespace: __NAMESPACE__
  labels:
    app: __APP_NAME__
    version: "__VERSION__"
spec:
  selector:
    app: __APP_NAME__
  ports:
    - name: https
      port: 443
      targetPort: 8080
      protocol: TCP
